'use client';
import {useState} from 'react';
import {Activity,Bell,Bot,CalendarDays,Check,ChevronDown,CircleDollarSign,Clock3,GripVertical,LayoutDashboard,Megaphone,MessageCircle,MoreHorizontal,Plus,Search,Send,Settings,Sparkles,TrendingUp,Users,WandSparkles,X} from 'lucide-react';

type View='Dashboard'|'Conversas'|'Agenda'|'CRM & Funil'|'Reativação'|'Campanhas'|'Relatórios'|'Configurar IA';
const nav:Array<[string,View,React.ElementType]>=[['VISÃO GERAL','Dashboard',LayoutDashboard],['','Conversas',MessageCircle],['','Agenda',CalendarDays],['RELACIONAMENTO','CRM & Funil',Users],['','Reativação',WandSparkles],['','Campanhas',Megaphone],['GESTÃO','Relatórios',Activity],['','Configurar IA',Bot]];
const people=[['Mariana Lopes','Quero saber sobre harmonização','Agora','ML'],['Carolina Mendes','Pode ser amanhã às 10h30','5 min','CM'],['Juliana Prado','Qual o valor do bioestimulador?','18 min','JP'],['Renata Vieira','Obrigada! Até sábado.','1 h','RV']];
const appointments=[['09:00','Mariana Lopes','Harmonização facial','Confirmado'],['10:30','Carolina Mendes','Avaliação estética','Confirmado'],['13:00','Juliana Prado','Bioestimulador','Aguardando'],['15:30','Renata Vieira','Retorno — Botox','Confirmado']];

export default function Home(){
 const [view,setView]=useState<View>('Dashboard'); const [query,setQuery]=useState(''); const [toast,setToast]=useState(''); const [selected,setSelected]=useState(0); const [reply,setReply]=useState('');
 const notify=(msg:string)=>{setToast(msg);setTimeout(()=>setToast(''),2400)};
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>Clini<span>IA</span></span></div><nav className="nav">{nav.map(([group,label,Icon])=><div key={label}>{group&&<p>{group}</p>}<button className={view===label?'active':''} onClick={()=>setView(label)}><Icon size={18}/><span>{label}</span>{label==='Conversas'&&<b>12</b>}</button></div>)}</nav><div className="clinic-card"><div className="clinic-avatar">IC</div><div><strong>Imperia Clinic</strong><small>Unidade Jardins</small></div><ChevronDown size={16}/></div></aside>
  <section className="content"><header className="topbar"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar paciente, conversa..."/><kbd>⌘ K</kbd></label><div className="top-actions"><button onClick={()=>setView('Configurar IA')} aria-label="Configurações"><Settings size={19}/></button><button className="notification" onClick={()=>notify('Você não tem novas notificações')} aria-label="Notificações"><Bell size={19}/><i/></button><div className="user-avatar">GF</div></div></header>
   <div className="page">{view==='Dashboard'&&<Dashboard go={setView}/>} {view==='Conversas'&&<Conversations query={query} selected={selected} setSelected={setSelected} reply={reply} setReply={setReply} notify={notify}/>} {view==='Agenda'&&<Agenda notify={notify}/>} {view==='CRM & Funil'&&<CRM notify={notify}/>} {view==='Reativação'&&<Reactivation notify={notify}/>} {view==='Campanhas'&&<Campaigns notify={notify}/>} {view==='Relatórios'&&<Reports/>} {view==='Configurar IA'&&<AISettings notify={notify}/>}</div>
  </section>{toast&&<div className="toast"><Check size={16}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
 </main>
}

function Heading({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:React.ReactNode}){return <div className="welcome section-heading"><div><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div>{action}</div>}

function Dashboard({go}:{go:(v:View)=>void}){const metrics=[['Conversas atendidas','1.284','+18,2%',MessageCircle],['Agendamentos','347','+12,4%',CalendarDays],['Taxa de conversão','27%','+4,1%',TrendingUp],['Receita atribuída','R$ 86,4 mil','+22,8%',CircleDollarSign]] as const;return <><Heading eyebrow="SÁBADO, 29 DE AGOSTO" title="Bom dia, Gabriela." text="Sua clínica está em movimento. Veja o que a IA fez por você." action={<button className="period"><CalendarDays size={16}/> Últimos 30 dias <ChevronDown size={15}/></button>}/><div className="metrics">{metrics.map(([l,v,t,I])=><article className="metric" key={l}><div className="metric-head"><span>{l}</span><i><I size={18}/></i></div><strong>{v}</strong><small><b>{t}</b> vs. período anterior</small></article>)}</div><div className="main-grid"><Funnel/><article className="panel ai-panel"><div className="ai-icon"><Bot size={22}/></div><span className="online"><i/> IA ATIVA</span><h2>Sua assistente não para.</h2><p>Nos últimos 30 minutos ela respondeu 8 clientes, negociou 3 objeções e fez 2 agendamentos.</p><div className="ai-stats"><div><b>98%</b><span>resolvido sem humano</span></div><div><b>1m 12s</b><span>tempo médio de resposta</span></div></div><button className="outline-btn" onClick={()=>go('Conversas')}>Ver conversas <span>→</span></button></article></div><div className="bottom-grid"><ScheduleMini go={go}/><Followup/></div></>}

function Funnel(){const data=[['Abordados',3840,100,'#173f37'],['Responderam',1267,72,'#2b7465'],['Agendaram',486,48,'#e98064'],['Compareceram',392,35,'#e8b656']] as const;return <article className="panel funnel-panel"><div className="panel-title"><div><h2>Funil de reativação</h2><p>Campanha <b>Clientes Inativos — Agosto</b></p></div><button><span className="live-dot"/> AO VIVO</button></div><div className="funnel-content"><div className="funnel-bars">{data.map(([l,v,p,c])=><div className="funnel-row" key={l}><div className="bar" style={{width:`${p}%`,background:c}}><span>{v.toLocaleString('pt-BR')}</span></div><label>{l}</label></div>)}</div><div className="campaign-return"><span>RETORNO DA CAMPANHA</span><strong>R$ 48.720</strong><p><b>8,4x</b> retorno sobre investimento</p><hr/><div><span>Investido <b>R$ 5.800</b></span><span>Ticket médio <b>R$ 124</b></span></div></div></div></article>}
function ScheduleMini({go}:{go:(v:View)=>void}){return <article className="panel schedule-panel"><div className="panel-title"><div><h2>Agenda de hoje</h2><p>4 atendimentos • 3 confirmados</p></div><button className="link-btn" onClick={()=>go('Agenda')}>Ver agenda completa →</button></div><div className="appointments">{appointments.map(([t,n,p,s])=><div className="appointment" key={t}><time>{t}</time><div className="patient-avatar sage">{n.split(' ').map(x=>x[0]).join('')}</div><div className="patient"><b>{n}</b><span>{p}</span></div><span className={`status ${s==='Confirmado'?'confirmed':'waiting'}`}><i/>{s}</span><button><MoreHorizontal size={19}/></button></div>)}</div></article>}
function Followup(){return <article className="panel followup-panel"><div className="panel-title"><div><h2>Follow-ups de hoje</h2><p>A IA cuidará de todos automaticamente</p></div><span className="auto"><Bot size={14}/> AUTOMÁTICO</span></div><div className="followup-list">{[['18 leads','1º retorno • após 1 dia','10:00',MessageCircle,'green'],['11 leads','2º retorno • após 3 dias','14:00',Clock3,'orange'],['7 leads','Última tentativa • após 7 dias','17:30',Sparkles,'yellow']].map(([a,b,c,I,color]:any)=><div key={a}><span className={`follow-icon ${color}`}><I size={17}/></span><p><b>{a}</b><small>{b}</small></p><strong>{c}</strong></div>)}</div><div className="chips"><span><i className="chip-on"/> 5 chips conectados</span><span>Rotação saudável</span></div></article>}

function Conversations({query,selected,setSelected,reply,setReply,notify}:any){const filtered=people.filter(p=>p[0].toLowerCase().includes(query.toLowerCase()));return <><Heading eyebrow="ATENDIMENTO 24H" title="Conversas" text="Acompanhe em tempo real e assuma quando quiser." action={<button className="primary-btn" onClick={()=>notify('Nova conversa iniciada')}><Plus size={15}/> Nova conversa</button>}/><div className="conversation-layout panel"><div className="conversation-list"><div className="list-tabs"><b>Todas</b><span>Não lidas 12</span></div>{filtered.map((p,i)=><button key={p[0]} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><div className="patient-avatar peach">{p[3]}</div><div><b>{p[0]}</b><span>{p[1]}</span></div><time>{p[2]}</time></button>)}</div><div className="chat"><div className="chat-head"><div className="patient-avatar sage">{people[selected][3]}</div><div><b>{people[selected][0]}</b><span><i/> online agora</span></div><button className="secondary-btn" onClick={()=>notify('Atendimento transferido para você')}>Assumir conversa</button></div><div className="messages"><div className="message client">Olá! Queria entender melhor como funciona e saber os valores.</div><div className="message ai"><small><Bot size={12}/> CLINIIA</small>Oi, {people[selected][0].split(' ')[0]}! Claro, vou te explicar tudo 😊 O procedimento é personalizado após uma avaliação. Posso verificar os melhores horários para você?</div><div className="message client">Pode ser amanhã pela manhã?</div><div className="message ai">Temos 10h30 disponível. Posso reservar para você?</div></div><form className="reply" onSubmit={e=>{e.preventDefault();if(reply){notify('Mensagem enviada');setReply('')}}}><input value={reply} onChange={e=>setReply(e.target.value)} placeholder="Digite uma mensagem..."/><button><Send size={16}/></button></form></div><aside className="contact-info"><div className="big-avatar">{people[selected][3]}</div><h3>{people[selected][0]}</h3><span>Lead via Instagram</span><hr/><label>TELEFONE<b>(11) 99845-2031</b></label><label>INTERESSE<b>Harmonização facial</b></label><label>ETAPA DO FUNIL<b className="tag">Em negociação</b></label><button className="secondary-btn" onClick={()=>notify('Contato aberto no CRM')}>Ver no CRM</button></aside></div></>}

function Agenda({notify}:any){const [day,setDay]=useState(29);return <><Heading eyebrow="AGENDA INTELIGENTE" title="Agenda" text="Confirmações e lembretes automáticos em um só lugar." action={<button className="primary-btn" onClick={()=>notify('Novo agendamento criado')}><Plus size={15}/> Novo agendamento</button>}/><div className="calendar-strip panel">{[27,28,29,30,31,1,2].map((d,i)=><button className={day===d?'active':''} onClick={()=>setDay(d)} key={i}><span>{['QUI','SEX','SÁB','DOM','SEG','TER','QUA'][i]}</span><b>{d}</b></button>)}</div><div className="agenda-grid"><article className="panel day-schedule"><div className="panel-title"><div><h2>{day===29?'Sábado, 29 de agosto':`Dia ${day}`}</h2><p>{day===29?'4 atendimentos agendados':'Nenhum atendimento agendado'}</p></div></div>{day===29?appointments.map(([t,n,p,s])=><div className="agenda-event" key={t}><time>{t}</time><div className="event-line"/><div><b>{n}</b><span>{p} • 60 min</span></div><span className={`status ${s==='Confirmado'?'confirmed':'waiting'}`}>{s}</span><button className="secondary-btn" onClick={()=>notify('Lembrete enviado pelo WhatsApp')}>Enviar lembrete</button></div>):<div className="empty"><CalendarDays/><b>Agenda livre</b><span>Selecione outro dia ou crie um agendamento.</span></div>}</article><aside className="panel summary-card"><h2>Resumo do dia</h2><div><span>Confirmados<b>3</b></span><span>Aguardando<b>1</b></span><span>Horários livres<b>4</b></span></div><hr/><p><Bot size={17}/> A IA enviará a confirmação dos atendimentos de amanhã às 18h.</p></aside></div></>}

function CRM({notify}:any){const initial=[{name:'Novos leads',leads:['Amanda Costa','Fernanda Lima','Bianca Rosa']},{name:'Em contato',leads:['Paula Martins','Larissa Souza']},{name:'Em negociação',leads:['Mariana Lopes','Juliana Prado']},{name:'Agendados',leads:['Carolina Mendes','Renata Vieira']}];const [cols,setCols]=useState(initial);const move=(ci:number,li:number)=>{if(ci===cols.length-1)return;const next=cols.map(c=>({...c,leads:[...c.leads]}));const [lead]=next[ci].leads.splice(li,1);next[ci+1].leads.push(lead);setCols(next);notify(`${lead} avançou para ${next[ci+1].name}`)};return <><Heading eyebrow="CRM VISUAL" title="Funil de vendas" text="Clique na seta de um lead para avançá-lo à próxima etapa." action={<button className="primary-btn" onClick={()=>notify('Novo lead adicionado')}><Plus size={15}/> Adicionar lead</button>}/><div className="kanban">{cols.map((col,ci)=><section key={col.name} className="kanban-col"><header><span className={`dot dot-${ci}`}/><b>{col.name}</b><em>{col.leads.length}</em></header>{col.leads.map((lead,li)=><article className="lead-card" key={lead}><div><GripVertical size={14}/><span className="patient-avatar sage">{lead.split(' ').map(x=>x[0]).join('')}</span><b>{lead}</b></div><p>Interesse: {li%2?'Botox':'Harmonização facial'}</p><small>Há {li+1} dia{li?'s':''} • Instagram</small>{ci<3&&<button onClick={()=>move(ci,li)}>Avançar →</button>}</article>)}</section>)}</div></>}

function Reactivation({notify}:any){const [campaign,setCampaign]=useState('Clientes Inativos — Agosto');return <><Heading eyebrow="RECUPERAÇÃO DE RECEITA" title="Reativação de contatos" text="Acompanhe cada etapa e o retorno financeiro em tempo real." action={<button className="primary-btn" onClick={()=>notify('Nova reativação configurada')}><Plus size={15}/> Nova reativação</button>}/><label className="select-label">Campanha ativa<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option>Clientes Inativos — Agosto</option><option>Retorno Botox — Trimestre</option><option>Avaliações não fechadas</option></select></label><div className="main-grid react-grid"><Funnel/><article className="panel reactivation-live"><span className="online-dark"><i/> PROCESSANDO AGORA</span><h2>Atividade ao vivo</h2>{['Mensagem enviada para Ana Clara','Beatriz respondeu à campanha','Novo agendamento: Camila Reis','Follow-up programado para Patrícia'].map((x,i)=><div key={x}><span>{i%2?<MessageCircle/>:<Send/>}</span><p><b>{x}</b><small>há {i+1} min</small></p></div>)}</article></div><div className="metrics mini-metrics"><article className="metric"><span>Taxa de resposta</span><strong>33%</strong></article><article className="metric"><span>Conversão em agenda</span><strong>38,4%</strong></article><article className="metric"><span>Comparecimento</span><strong>80,6%</strong></article><article className="metric"><span>ROI</span><strong>8,4x</strong></article></div></>}

function Campaigns({notify}:any){const [active,setActive]=useState([true,true,false]);const rows=[['Clientes Inativos — Agosto','3.840','1.267','486','R$ 48.720'],['Retorno Botox — Trimestre','1.220','438','192','R$ 31.480'],['Semana da Harmonização','2.500','—','—','—']];return <><Heading eyebrow="WHATSAPP EM ESCALA" title="Campanhas" text="Disparos com rotação inteligente dos seus 5 chips." action={<button className="primary-btn" onClick={()=>notify('Rascunho de campanha criado')}><Plus size={15}/> Criar campanha</button>}/><div className="chip-health panel"><div><i/><b>5 chips conectados</b><span>Aquecimento e rotação saudáveis</span></div>{[1,2,3,4,5].map(n=><span key={n}>CHIP {n}<b>Online</b></span>)}</div><article className="panel table-panel"><div className="panel-title"><div><h2>Suas campanhas</h2><p>Resultados atualizados em tempo real</p></div></div><div className="data-table"><header><span>CAMPANHA</span><span>ENVIADOS</span><span>RESPOSTAS</span><span>AGENDADOS</span><span>RECEITA</span><span>STATUS</span></header>{rows.map((r,i)=><div key={r[0]}>{r.map(x=><span key={x}>{x}</span>)}<button className={`switch ${active[i]?'on':''}`} onClick={()=>setActive(a=>a.map((v,j)=>j===i?!v:v))}><i/></button></div>)}</div></article></>}

function Reports(){const [period,setPeriod]=useState('Agosto 2026');return <><Heading eyebrow="VISÃO ESTRATÉGICA" title="Relatórios" text="Saiba exatamente de onde vêm seus agendamentos." action={<select className="period select" value={period} onChange={e=>setPeriod(e.target.value)}><option>Agosto 2026</option><option>Julho 2026</option><option>Junho 2026</option></select>}/><div className="metrics"><article className="metric"><span>Receita no período</span><strong>R$ 124.850</strong><small><b>+18%</b> vs. mês anterior</small></article><article className="metric"><span>Novos agendamentos</span><strong>347</strong><small><b>+12%</b> vs. mês anterior</small></article><article className="metric"><span>Ticket médio</span><strong>R$ 360</strong><small><b>+5%</b> vs. mês anterior</small></article><article className="metric"><span>Retorno da IA</span><strong>R$ 86.400</strong><small>69% da receita total</small></article></div><div className="report-grid"><article className="panel source-chart"><h2>Origem dos agendamentos</h2>{[['Instagram',42,'#e98064'],['Reativação',27,'#2b7465'],['Indicação',18,'#e8b656'],['Google',9,'#7d91a0'],['Outros',4,'#c9c6bb']].map(([n,p,c]:any)=><div key={n}><span>{n}</span><div><i style={{width:`${p}%`,background:c}}/></div><b>{p}%</b></div>)}</article><article className="panel source-table"><h2>Desempenho por origem</h2><div><span>Instagram<b>146 agend.</b></span><strong>R$ 52.560</strong></div><div><span>Reativação<b>94 agend.</b></span><strong>R$ 33.840</strong></div><div><span>Indicação<b>62 agend.</b></span><strong>R$ 22.320</strong></div><div><span>Google<b>31 agend.</b></span><strong>R$ 11.160</strong></div></article></div></>}

function AISettings({notify}:any){const [toggles,setToggles]=useState([true,true,true,true]);const labels=[['Atendimento automático 24h','Responder novas mensagens com linguagem natural.'],['Quebra de objeções','Negociar valores dentro do limite autorizado.'],['Confirmação de agenda','Confirmar automaticamente no dia anterior.'],['Follow-up inteligente','Retornar em 1, 3 e 7 dias para quem não respondeu.']];return <><Heading eyebrow="PERSONALIDADE E AUTOMAÇÕES" title="Configurar IA" text="Defina como sua assistente conversa, negocia e acompanha cada cliente."/><div className="settings-grid"><article className="panel settings-card"><h2>Assistente virtual</h2><label>Nome da assistente<input defaultValue="Lívia"/></label><label>Tom de voz<select defaultValue="acolhedor"><option value="acolhedor">Acolhedor e profissional</option><option>Direto e objetivo</option><option>Leve e descontraído</option></select></label><label>Mensagem de apresentação<textarea defaultValue="Olá! Eu sou a Lívia, assistente virtual da Imperia Clinic. Como posso ajudar você hoje?"/></label></article><article className="panel settings-card"><h2>Automações</h2>{labels.map(([a,b],i)=><div className="setting-row" key={a}><div><b>{a}</b><span>{b}</span></div><button className={`switch ${toggles[i]?'on':''}`} onClick={()=>setToggles(t=>t.map((v,j)=>j===i?!v:v))}><i/></button></div>)}</article><article className="panel settings-card full"><h2>Limites de negociação</h2><div className="limit-grid"><label>Desconto máximo permitido<div className="input-suffix"><input type="number" defaultValue="10"/><span>%</span></div></label><label>Valor mínimo de entrada<div className="input-suffix"><span>R$</span><input type="number" defaultValue="200"/></div></label><label>Máximo de parcelas<select defaultValue="6"><option>3</option><option>6</option><option>10</option></select></label></div></article></div><div className="save-bar"><span>Alterações salvas automaticamente neste dispositivo.</span><button className="primary-btn" onClick={()=>notify('Configurações da IA salvas')}>Salvar configurações</button></div></>}
