'use client';
import { Activity,Bell,Bot,CalendarDays,ChevronDown,CircleDollarSign,Clock3,LayoutDashboard,Megaphone,MessageCircle,MoreHorizontal,Search,Settings,Sparkles,TrendingUp,Users,WandSparkles } from 'lucide-react';

const metrics=[['Conversas atendidas','1.284','+18,2%',MessageCircle],['Agendamentos','347','+12,4%',CalendarDays],['Taxa de conversão','27%','+4,1%',TrendingUp],['Receita atribuída','R$ 86,4 mil','+22,8%',CircleDollarSign]] as const;
const funnel=[['Abordados',3840,100,'#173f37'],['Responderam',1267,72,'#2b7465'],['Agendaram',486,48,'#e98064'],['Compareceram',392,35,'#e8b656']] as const;
const schedule=[['09:00','Mariana Lopes','Harmonização facial','Confirmado','ML','peach'],['10:30','Carolina Mendes','Avaliação estética','Confirmado','CM','sage'],['13:00','Juliana Prado','Bioestimulador','Aguardando','JP','sun'],['15:30','Renata Vieira','Retorno — Botox','Confirmado','RV','lavender']] as const;

export default function Home(){return <main className="app-shell">
 <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>Clini<span>IA</span></span></div><nav className="nav"><p>VISÃO GERAL</p><a className="active"><LayoutDashboard size={18}/> Dashboard</a><a><MessageCircle size={18}/> Conversas <b>12</b></a><a><CalendarDays size={18}/> Agenda</a><p>RELACIONAMENTO</p><a><Users size={18}/> CRM & Funil</a><a><WandSparkles size={18}/> Reativação</a><a><Megaphone size={18}/> Campanhas</a><p>GESTÃO</p><a><Activity size={18}/> Relatórios</a><a><Bot size={18}/> Configurar IA</a></nav><div className="clinic-card"><div className="clinic-avatar">IC</div><div><strong>Imperia Clinic</strong><small>Unidade Jardins</small></div><ChevronDown size={16}/></div></aside>
 <section className="content"><header className="topbar"><div className="search"><Search size={17}/><span>Buscar paciente, conversa...</span><kbd>⌘ K</kbd></div><div className="top-actions"><button aria-label="Configurações"><Settings size={19}/></button><button className="notification" aria-label="Notificações"><Bell size={19}/><i/></button><div className="user-avatar">GF</div></div></header>
 <div className="page"><div className="welcome"><div><p>SÁBADO, 29 DE AGOSTO</p><h1>Bom dia, Gabriela.</h1><span>Sua clínica está em movimento. Veja o que a IA fez por você.</span></div><button className="period"><CalendarDays size={16}/> Últimos 30 dias <ChevronDown size={15}/></button></div>
 <div className="metrics">{metrics.map(([label,value,trend,Icon])=><article className="metric" key={label}><div className="metric-head"><span>{label}</span><i><Icon size={18}/></i></div><strong>{value}</strong><small><b>{trend}</b> vs. período anterior</small></article>)}</div>
 <div className="main-grid"><article className="panel funnel-panel"><div className="panel-title"><div><h2>Funil de reativação</h2><p>Campanha <b>Clientes Inativos — Agosto</b></p></div><button><span className="live-dot"/> AO VIVO</button></div><div className="funnel-content"><div className="funnel-bars">{funnel.map(([label,value,percent,color])=><div className="funnel-row" key={label}><div className="bar" style={{width:`${percent}%`,background:color}}><span>{value.toLocaleString('pt-BR')}</span></div><label>{label}</label></div>)}</div><div className="campaign-return"><span>RETORNO DA CAMPANHA</span><strong>R$ 48.720</strong><p><b>8,4x</b> retorno sobre investimento</p><hr/><div><span>Investido <b>R$ 5.800</b></span><span>Ticket médio <b>R$ 124</b></span></div></div></div></article>
 <article className="panel ai-panel"><div className="ai-icon"><Bot size={22}/></div><span className="online"><i/> IA ATIVA</span><h2>Sua assistente não para.</h2><p>Nos últimos 30 minutos ela respondeu 8 clientes, negociou 3 objeções e fez 2 agendamentos.</p><div className="ai-stats"><div><b>98%</b><span>resolvido sem humano</span></div><div><b>1m 12s</b><span>tempo médio de resposta</span></div></div><button className="outline-btn">Ver conversas <span>→</span></button></article></div>
 <div className="bottom-grid"><article className="panel schedule-panel"><div className="panel-title"><div><h2>Agenda de hoje</h2><p>4 atendimentos • 3 confirmados</p></div><button className="link-btn">Ver agenda completa →</button></div><div className="appointments">{schedule.map(([time,name,procedure,status,initials,tone])=><div className="appointment" key={time}><time>{time}</time><div className={`patient-avatar ${tone}`}>{initials}</div><div className="patient"><b>{name}</b><span>{procedure}</span></div><span className={`status ${status==='Confirmado'?'confirmed':'waiting'}`}><i/>{status}</span><button aria-label="Mais opções"><MoreHorizontal size={19}/></button></div>)}</div></article>
 <article className="panel followup-panel"><div className="panel-title"><div><h2>Follow-ups de hoje</h2><p>A IA cuidará de todos automaticamente</p></div><span className="auto"><Bot size={14}/> AUTOMÁTICO</span></div><div className="followup-list"><div><span className="follow-icon green"><MessageCircle size={17}/></span><p><b>18 leads</b><small>1º retorno • após 1 dia</small></p><strong>10:00</strong></div><div><span className="follow-icon orange"><Clock3 size={17}/></span><p><b>11 leads</b><small>2º retorno • após 3 dias</small></p><strong>14:00</strong></div><div><span className="follow-icon yellow"><Sparkles size={17}/></span><p><b>7 leads</b><small>Última tentativa • após 7 dias</small></p><strong>17:30</strong></div></div><div className="chips"><span><i className="chip-on"/> 5 chips conectados</span><span>Rotação saudável</span></div></article></div>
 </div></section></main>}
